# Generated by Django 2.2.6 on 2021-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('LUNCH', 'Lunch'), ('BREAKFAST', 'Breakfast'), ('DINNER', 'Dinner'), ('SNACK', 'Snack'), ('DESSERT', 'Dessert')], default='Dinner', max_length=30),
        ),
    ]
