# Generated by Django 2.2.6 on 2021-06-27 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('LUNCH', 'Lunch'), ('BREAKFAST', 'Breakfast'), ('DINNER', 'Dinner'), ('SNACK', 'Snack'), ('DESSERT', 'Dessert')], default='Dinner', max_length=20),
        ),
    ]
