# Generated by Django 2.2.6 on 2021-06-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='date_posted',
        ),
    ]
